"use strict";var Q=Object.defineProperty;var F=Object.getOwnPropertyDescriptor;var v=Object.getOwnPropertyNames;var V=Object.prototype.hasOwnProperty;var M=(u,s)=>{for(var c in s)Q(u,c,{get:s[c],enumerable:!0})},G=(u,s,c,e)=>{if(s&&typeof s=="object"||typeof s=="function")for(let o of v(s))!V.call(u,o)&&o!==c&&Q(u,o,{get:()=>s[o],enumerable:!(e=F(s,o))||e.enumerable});return u};var Y=u=>G(Q({},"__esModule",{value:!0}),u);var K={};M(K,{default:()=>q});module.exports=Y(K);var n=require("@raycast/api"),S=require("react");var a=require("@raycast/api"),g=require("react");var L={title:"\u{1F6A8}"},$={title:"\u{1F50D}",message:"Answering your question"},T={title:"\u2705",message:"Answer has been saved!"};function R(){return`q-${Date.now()}`}var B="You answer questions about a YouTube video based on its transcript. Be concise and direct.";function N(u,s,c="",e=[]){let o=e.length>0?`
Previous Q&A:
${e.map(t=>`Q: ${t.question}
A: ${t.answer}`).join(`

`)}
`:"";return`${B}

Video transcript:
${s}

Your summary:
${c}
${o}
Question: ${u}`}var p=require("react/jsx-runtime");function E({transcript:u,questions:s,onQuestionsUpdate:c}){let[e,o]=(0,g.useState)(""),[t,l]=(0,g.useState)(s),[d,i]=(0,g.useState)(s[0]?.id??"");(0,g.useEffect)(()=>{c?.(t)},[t,c]);let f=async()=>{if(!e)return;let r=R(),I=e,x=await(0,a.showToast)({style:a.Toast.Style.Animated,title:$.title,message:$.message}),P=t[0]?.answer||"",U=t.slice(1).map(m=>({question:m.question,answer:m.answer})),D=a.AI.ask(N(I,u,P,U));l(m=>[{id:r,question:I,answer:""},...m]),o("");let _=!0;D.on("data",m=>{_&&(x.show(),_=!1),l(C=>{let A=C.slice();return A[0]={...A[0],answer:A[0].answer+m},A})}),D.finally(()=>{x.hide(),i(r)})},w=()=>t.length?`Questions:
${t.map(r=>`Q: ${r.question}
A: ${r.answer}`).join(`

`)}`:"",H=()=>{let r=t.find(I=>I.id===d);return r?r.id===t[0]?.id?r.answer:`Q: ${r.question}
A: ${r.answer}`:""};return(0,p.jsx)(a.List,{filtering:!1,isShowingDetail:!0,navigationTitle:"Additional Questions",onSearchTextChange:o,searchText:e,searchBarPlaceholder:"Ask another question",selectedItemId:d,searchBarAccessory:(0,p.jsxs)(a.ActionPanel,{children:[(0,p.jsx)(a.Action.SubmitForm,{onSubmit:f,title:"Ask"}),(0,p.jsx)(a.Action.CopyToClipboard,{title:"Copy Selected Answer",content:H()}),(0,p.jsx)(a.Action.CopyToClipboard,{title:"Copy All Q&A",content:w()})]}),children:t.map(r=>(0,p.jsx)(a.List.Item,{title:r.question,detail:(0,p.jsx)(a.List.Item.Detail,{markdown:r.answer}),id:r.id},r.id))})}var h=require("@raycast/api"),O="youtube-summary-",b="youtube-summary-keys",k=()=>{let u=async e=>{let o=`${e.id}-${e.aiService}`;await h.LocalStorage.setItem(`${O}${o}`,JSON.stringify(e));let t=await c();t.includes(o)||(t.unshift(o),await h.LocalStorage.setItem(b,JSON.stringify(t)))},s=async()=>{let e=await c();return(await Promise.all(e.map(async t=>{let l=await h.LocalStorage.getItem(`${O}${t}`);if(!l)return null;let d=JSON.parse(l);return d.createdAt=new Date(d.createdAt),d}))).filter(t=>t!==null).sort((t,l)=>l.createdAt.getTime()-t.createdAt.getTime())},c=async()=>{let e=await h.LocalStorage.getItem(b);return e?JSON.parse(e):[]};return{addToHistory:u,getHistory:s}};var y=require("react/jsx-runtime");function q(){let[u,s]=(0,S.useState)([]),[c,e]=(0,S.useState)(!0),{getHistory:o,addToHistory:t}=k();(0,S.useEffect)(()=>{d()},[]);async function l(i,f){try{let w={...i,questions:f,createdAt:new Date};await t(w),await d(),await(0,n.showToast)({style:n.Toast.Style.Success,title:T.title,message:T.message})}catch(w){await(0,n.showToast)({style:n.Toast.Style.Failure,title:L.title,message:String(w)})}}async function d(){try{let i=await o();s(i)}catch(i){await(0,n.showToast)({style:n.Toast.Style.Failure,title:"Failed to load history",message:String(i)})}finally{e(!1)}}return(0,y.jsx)(n.List,{isLoading:c,children:u.map(i=>(0,y.jsx)(n.List.Item,{icon:n.Icon.Video,title:i.title,subtitle:new Date(i.createdAt).toLocaleDateString(),accessories:[{text:i.aiService}],actions:(0,y.jsx)(n.ActionPanel,{children:(0,y.jsx)(n.Action.Push,{icon:n.Icon.Document,title:"Check Details",target:(0,y.jsx)(E,{transcript:i.summary,questions:i.questions,onQuestionsUpdate:f=>l(i,f)})})})},`${i.id}-${i.aiService}`))})}
