set -g default-terminal "screen-256color"

# prefix key change
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

set -g pane-border-style 'fg=colour235' 
set -g pane-active-border-style 'fg=colour238'
# better escape responsiveness
set -s escape-time 0

# creates new window in current directory
bind c new-window -c '#{pane_current_path}'

# change horizontal split to =
unbind %
unbind =
bind = split-window -h -c '#{pane_current_path}'

# change vertical split to -
unbind '"'
bind - split-window -v -c '#{pane_current_path}'

# changes tmux session directory
unbind z
bind z attach-session -t . -c '#{pane_current_path}'

# sourcing config file
bind r source-file ~/.tmux.conf
# install new packages using prefix + I
# source using prefix + r

# resizing panels
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
bind -r m resize-pane -Z
set -g mouse on

# allows clearing screen after prefix
bind C-l send-keys 'C-l'


# allow vim mode keys in tmux
unbind v
bind v copy-mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection  # visual mode selection
bind-key -T copy-mode-vi 'y' send -X copy-selection   # yank for copy

unbind -T copy-mode-vi MouseDragEnd1Pane

#reorder windows
set-option -g renumber-windows on
#start windows at 1 instead of 0
set -g base-index 1
setw -g pane-base-index 1


# plugin manager
set -g @plugin 'tmux-plugins/tpm'

# list of tmux plugins
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'  # persist tmux sessions after computer restart
set -g @plugin 'tmux-plugins/tmux-continuum'  # automatically saves session for you every 15 minutes
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

# themes
set -g @minimal-tmux-bg "#DADADA"
set -g @plugin 'niksingh710/minimal-tmux-status'
set -g window-status-style bg=default
set status-bg default
# toggle tmux status bar at the bottom
bind-key b set-option status


# initialize plugin manager (make sure this is at the end of the file)
run -b '~/.tmux/plugins/tpm/tpm'

